region: eu-west-1
domain: mojalabs.io
tenant: labs11
enable_github_oauth: false
enable_netmaker_oidc: true
ansible_collection_tag: v0.16.11
gitlab_admin_rbac_group: tenant-admins
gitlab_readonly_rbac_group: tenant-viewers
smtp_server_enable: false
gitlab_version: 16.0.5
gitlab_runner_version: 16.0.2
iac_group_name: iac_admin
netmaker_version: 0.18.7
letsencrypt_email: test@mojalabs.io
delete_storage_on_term: true
envs:
  - env: dev
    domain: labsk8s604.mojaloop.live
    cloud_platform: aws
    managed_svc_cloud_platform: aws
    cloud_platform_client_secret_name: AWS_SECRET_ACCESS_KEY
    k8s_cluster_module: base-k8s
    cloud_region: eu-west-1
    k8s_cluster_type: microk8s
    ansible_collection_tag: v0.16.11
    iac_terraform_modules_tag: v0.30.4
    enable_vault_oauth_to_gitlab: true
    enable_grafana_oauth_to_gitlab: true
    letsencrypt_email: test@mojalabs.io
    dns_zone_force_destroy: true
    longhorn_backup_object_store_destroy: true
    agent_instance_type: "m5.2xlarge"
    master_instance_type: "m5.4xlarge"
    master_node_count: 3
    agent_node_count: 0
    vpc_cidr: "10.106.0.0/23"
    enable_k6s_test_harness: false
    k6s_docker_server_instance_type: "m5.2xlarge"
tags:
  {
    "Origin": "Terraform",
    "mojaloop/cost_center": "mlf-iac-sandbox",
    "mojaloop/env": "ft-sbox-rw",
    "mojaloop/owner": "Samuel-Kummary",
  }
